version: "3"

networks:
  image_search:
    external: false

services:
  frontend:
    build: ./frontend
    environment:
      API_UPSTREAM: backend
    restart: always
    networks:
      - image_search
    ports:
      - 8080:80
    depends_on:
       - backend

  backend:
    build: ./backend
    environment:
      MONGODB_LOGIN: image_search
      MONGODB_PASSWORD: image_search_password
      MONGODB_DB: image_search
      MONGODB_HOST: db
    restart: always
    networks:
      - image_search
    depends_on:
       - db

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: image_search
    networks:
      - image_search
    volumes:
      - mongo_db:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_db:
