version: "3"

services:
  frontend:
    build: ./frontend
    environment:
      API_UPSTREAM_ADDR: backend
      API_UPSTREAM_PORT: 8080
      S3_ADDR: minio
      S3_PORT: 9000
      NGINX_PORT: 10000
    networks:
      - image_search
    ports:
      - 10000:10000
    depends_on:
       - backend
    restart: on-failure

  backend:
    build: ./backend
    environment:
      MONGODB_LOGIN: ${MONGODB_LOGIN:-image_search}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-image_search_password}
      MONGODB_DB: ${MONGODB_DB:-image_search}
      MONGODB_HOST: db
      S3_ENDPOINT: 'http://minio:9000'
      S3_ACCESS_KEY: ${MINIO_ROOT_USER:-image_search}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-image_search_password}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-120}
    networks:
      - image_search
    depends_on:
       - db
       - minio
    restart: on-failure

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-image_search}
    networks:
      - image_search
    volumes:
      - ./run/mongo_db:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: on-failure

  minio:
    image: minio/minio
    networks:
      - image_search
    volumes:
      - ./run/minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-image_search}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-image_search_password}
    entrypoint: sh
    command: -c 'mkdir -p /data/image-search && minio server --console-address ":9001" /data'
    restart: on-failure

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - image_search
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 image_search image_search_password;
      /usr/bin/mc mb myminio/image-search;
      /usr/bin/mc anonymous set download myminio/image-search;
      exit 0;
      "

networks:
  image_search:
    external: false
