version: "3"

networks:
  image_search:
    external: false

services:
  frontend:
    build: ./frontend
    environment:
      API_UPSTREAM_ADDR: backend
      API_UPSTREAM_PORT: 8080
      S3_ADDR: minio
      S3_PORT: 9000
    restart: always
    networks:
      - image_search
    ports:
      - 8080:80
    depends_on:
       - backend

  backend:
    build: ./backend
    environment:
      MONGODB_LOGIN: image_search
      MONGODB_PASSWORD: image_search_password
      MONGODB_DB: image_search
      MONGODB_HOST: db
    restart: always
    networks:
      - image_search
    depends_on:
       - db
       - minio

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: image_search
    networks:
      - image_search
    volumes:
      - mongo_db:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  minio:
    image: minio/minio
    networks:
      - image_search
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: image_search
      MINIO_ROOT_PASSWORD: image_search_password
    command: server --console-address ":9001" /data

volumes:
  mongo_db:
  minio_data:
