version: "3"

services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: image_search
    volumes:
    network_mode: host
    restart: on-failure
    volumes:
      - ./run/mongo_db:/data/db
      - ../scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  minio:
    image: minio/minio
    network_mode: host
    restart: on-failure
    volumes:
      - ./run/minio_data:/data
    environment:
      MINIO_ROOT_USER: image_search
      MINIO_ROOT_PASSWORD: image_search_password
    entrypoint: sh
    command: -c 'mkdir -p /data/image-search && minio server --console-address ":9001" /data'

  nginx:
    image: nginx
    network_mode: host
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    network_mode: host
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://localhost:9000 image_search image_search_password;
      /usr/bin/mc mb myminio/image-search;
      /usr/bin/mc anonymous set download myminio/image-search;
      exit 0;
      "
