version: "3"

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: image_search
    network_mode: host
    volumes:
      - ../../scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
