version: "3"

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: image_search
    network_mode: host
    volumes:
      - ../../scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  minio:
    image: minio/minio
    network_mode: host
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: image_search
      MINIO_ROOT_PASSWORD: image_search_password
    command: server --console-address ":9001" /data

  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
